services:
    cup-web-build:
        container_name: cup-web-build
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./cup-web/:/var/www/html
            - ./docker/config/apache2/apache2.conf:/etc/apache2/apache2.conf
        command: >
            bash -c "
            chmod u+x /var/www/html/entrypointBEBuild.sh &&
            /var/www/html/entrypointBEBuild.sh"
        networks:
            - cup-db-network
        depends_on:
          cup-db:
            condition: service_healthy

    cup-db:
        container_name: cup-db
        image: mariadb:12.1.1-ubi-rc
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./docker/cup-mariadb:/var/lib/mysql
        networks:
            - cup-db-network
        healthcheck:
          test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
          # test: ["CMD", "healthcheck.sh", "--connect"]
          start_period: 20s
          interval: 15s
          timeout: 5s
          retries: 5
networks:
    cup-db-network:
