services:
    cup-dev:
        depends_on:
            - cup-dev-db
        container_name: cup-dev
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "81:80"
            - "5173:5173"
            - "8000:8000"
        volumes:
            - ./VolleyLeague/:/var/www/html
        command: >
            bash -c "
            chmod u+x /var/www/html/entrypointBE.sh &&
            /var/www/html/entrypointBE.sh"
        networks:
            - cup-dev-network

    cup-dev-db:
        container_name: cup-dev-db
        image: mysql:8.0.37-debian
        environment:
            MYSQL_DATABASE: cup-dev-database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - ./docker/mysql-data:/var/lib/mysql
            - ./docker/config/mysql_ini:/docker-entrypoint-initdb.d
            - ./docker/config/mysql/my.cnf:/etc/my.cnf
        networks:
            - cup-dev-network
networks:
    cup-dev-network:
