services:
    cup-nginx:
        container_name: cup-nginx
        image: nginx:stable-alpine-perl
        volumes:
          - ./cup-web:/var/www/html
          - ./docker/nginx/logs:/var/log/nginx
          - ./docker/nginx/conf.d:/etc/nginx/conf.d
        restart: always
        ports:
          - 80:80
        networks:
          - cup-nginx-network
    cup-web:
        depends_on:
            - cup-db
        container_name: cup-web
        build:
            context: .
            dockerfile: DockerfileWebDeploy
        volumes:
            - ./cup-web/:/var/www/html
        networks:
            - cup-db-network
            - cup-nginx-network
        depends_on:
          cup-db:
            condition: service_healthy

    cup-db:
        container_name: cup-db
        image: mariadb:12.1.1-ubi-rc
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./docker/cup-mariadb:/var/lib/mysql
        networks:
            - cup-db-network
        healthcheck:
          test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
          # test: ["CMD", "healthcheck.sh", "--connect"]
          start_period: 20s
          interval: 15s
          timeout: 5s
          retries: 5
networks:
    cup-db-network:
    cup-nginx-network:
