services:
    sports_leagues_sprint04:
        depends_on:
            - mysql
        container_name: sports_leagues-backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "81:80"
            - "5173:5173"
        volumes:
            - ./VolleyLeague/:/var/www/html
        command: >
            bash -c "
            chmod u+x /var/www/html/entrypointBE.sh &&
            /var/www/html/entrypointBE.sh"
        networks:
            - sprint04_network

    mysql:
        container_name: sprint04-mysql
        image: mysql:8.0.37-debian
        environment:
            MYSQL_DATABASE: sports_leagues_database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - ./docker/mysql-data:/var/lib/mysql
            - ./docker/config/mysql_ini:/docker-entrypoint-initdb.d
            - ./docker/config/mysql/my.cnf:/etc/my.cnf
        networks:
            - sprint04_network

networks:
    sprint04_network:
